

# name: CI/CD

# on:
#   push:
#     branches: [ develop ]
#   workflow_dispatch:
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - name: Use Node.js
#         uses: actions/setup-node@v3
#         with: 
#           node-version: "18.13.0"
#       - name: Install dependencies
#         run: npm install

#       - name: Run test
#         run: npm test



name: CI/CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - develop
  pull_request: 
    branches:
      - develop
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
    env: 
    
      MONGODB_URL: ${{secrets.MONGODB_URL}}
      CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
     CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
      CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
     
      PORT: ${{secrets.PORT}}
    steps:
      - uses: actions/checkout@v3
      - name: 'Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - run: npm run coverage




